# Generated by Django 4.2.5 on 2023-10-03 17:01

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(help_text='birthday of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(default='cat', help_text='breed of the cat', max_length=255),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True, help_text='description of the quality of the awesomeness of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(help_text='name of the cat', max_length=255),
        ),
    ]
